= Changelog

== v2.0.1, July 19th 2023

* Updated underlying Operator SDK to 1.30.0
* Code cleanup to fully qualified Ansible modules
* *BREAKING*: Changed variable `giteaRoute` to `giteaHostname`. It was really never a route that was provided. This makes is clearer what is expected to be set in the variable.
* Added capability to specify ImagePullPolicy for both PostgreSQL and Gitea images
** `postgresqlImagePullPolicy`, `giteaImagePullPolicy`
* Added capability to provide admin password via a secret
** `giteaAdminPasswordSecretName` specifies the name of a secret containing the Gitea admin user's password in secret key `adminPassword`. If this variable is set it takes precedence over all other ways to specify/generate an admin password.
* Added capability to provide user passwords via a secret
** `giteaUserPasswordSecretName` specifies the name of a secret containing the Gitea user common password in secret key `userPassword`. If this variable is set it takes precedence over all other ways to specify/generate a user password.
* Added flags to expose the passwords in the Gitea custom resource. The default for both flags is `true` for backward compability. This can be useful when setting the password(s) via a secret so that the password doesn't leak in the custom resource
** `giteaAdminPasswordExpose` and `giteaUserPasswordExpose`
* Added the capability to specify your own `app.ini` configuration file in a ConfigMap.
** `giteaConfigMapName`: Name of a config map in the same namespace as the Gitea custom resource. The config map must contain one file called `app.ini` to configure Gitea. If this variable is set then `giteaHostname` *must* also be set. `giteaSsl` should be set but will default to false.
* Enable customization of the Web Hook permissions. The Gitea default is to allow only external targets for a web hook and only with validated certificates. For connection _inside_ an OpenShift cluster this does not work.
** giteaWebhookAllowedHostList: List of hosts that a web hook is allowed to call. See https://docs.gitea.com/next/administration/config-cheat-sheet#webhook-webhook for more details. The default for the operator is 'external,private' allowing connections inside the clusetr as well.
** giteaWebhookSkipTlsVerify: Set to 'true' to skip validation of the webhook target URL certificate.
                    