apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "pfe.rhpds.com/v1",
          "kind": "Gitea",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "gitea-operator"
            },
            "name": "repository"
          },
          "spec": {
            "giteaImagePullPolicy": "Always",
            "giteaImageTag": "1.25.5.2",
            "giteaSsl": true,
            "giteaVolumeSize": "4Gi",
            "postgresqlVolumeSize": "4Gi"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-04-21T14:55:37Z"
    operators.operatorframework.io/builder: operator-sdk-v1.39.2
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: gitea-operator.v2.3.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Gitea
      name: gitea.pfe.rhpds.com
      version: v1
  description: Gitea Operator - provided by Red Hat Demo Platform, see https://github.com/rhpds/gitea-operator
    for documentation.
  displayName: Gitea Operator
  icon:
  - base64data: ""
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          - pods
          - pods/exec
          - pods/log
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - pfe.rhpds.com
          resources:
          - gitea
          - gitea/status
          - gitea/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          - persistentvolumeclaims
          - configmaps
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: gitea-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: gitea-operator
          control-plane: controller-manager
        name: gitea-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-require-rbac
                - --metrics-secure
                - --metrics-bind-address=:8443
                - --leader-elect
                - --leader-election-id=gitea-operator
                - --health-probe-bind-address=:6789
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/rhpds/gitea-operator:v2.3.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: "1"
                    memory: 2Gi
                  requests:
                    cpu: 200m
                    memory: 1Gi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: gitea-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: gitea-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - gitea
  - repository
  links:
  - name: Gitea Operator
    url: https://github.com/rhpds/gitea-operator
  maintainers:
  - email: wkulhane@redhat.com
    name: Wolfgang Kulhanek
  maturity: stable
  provider:
    name: Red Hat Portfolio Technical Marketing and Platforms
  replaces: gitea-operator.v2.3.1
  version: 2.3.1
