
---
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: gitea-operator.v0.0.0
  namespace: placeholder
spec:
  replaces: gitea-operator.v2.2.0
  maturity: stable
  icon:
  - base64data: 
    mediatype: image/svg+xml

